import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SessionProviderForNextAuth from "@/nextAuth/SessionProviderForNextAuth";
import ReduxStoreProvider from "@/redux/ReduxStoreProvider";
import background from "@/assets/images/background.png";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
  <body
    className={`
      ${geistSans.variable} 
      ${geistMono.variable} 
      antialiased 
      bg-cover 
      bg-center 
      bg-no-repeat 
      bg-fixed 
      min-h-screen 
      object-fill 
      text-white
    `}
    style={{
      backgroundImage: `url(${background.src})`,
      backgroundAttachment: "fixed", // ensures background stays fixed
      backgroundSize: "cover",
      backgroundPosition: "center",
      backgroundRepeat: "no-repeat",
    }}
  >
    <SessionProviderForNextAuth>
      <ReduxStoreProvider>
        <Toaster richColors />
        {children}
      </ReduxStoreProvider>
    </SessionProviderForNextAuth>
  </body>
</html>

  );
}
